export type Team = {
  id: string;
  code: string;
  name: string;
};

export type Match = {
  id: string;
  kickoffLabel: string;
  home: Team;
  away: Team;
};

export const WC2026_MATCHES: Match[] = [
  {
    id: "2026-06-11-A-01",
    kickoffLabel: "2026/6/11(木) グループA｜エスタディオ・アステカ（メキシコシティ）",
    home: { id: "MEX", code: "MEX", name: "メキシコ" },
    away: { id: "RSA", code: "RSA", name: "南アフリカ" },
  },
  {
    id: "2026-06-11-A-02",
    kickoffLabel: "2026/6/11(木) グループA｜エスタディオ・グアダラハラ",
    home: { id: "KOR", code: "KOR", name: "韓国" },
    away: { id: "FIFA_A", code: "FIFA", name: "FIFA A" },
  },
  {
    id: "2026-06-12-B-01",
    kickoffLabel: "2026/6/12(金) グループB｜トロント・スタジアム",
    home: { id: "CAN", code: "CAN", name: "カナダ" },
    away: { id: "FIFA_B", code: "FIFA", name: "FIFA B" },
  },
  {
    id: "2026-06-12-D-01",
    kickoffLabel: "2026/6/12(金) グループD｜ロサンゼルス・スタジアム",
    home: { id: "USA", code: "USA", name: "アメリカ" },
    away: { id: "PAR", code: "PAR", name: "パラグアイ" },
  },
  {
    id: "2026-06-13-C-01",
    kickoffLabel: "2026/6/13(土) グループC｜ボストン・スタジアム",
    home: { id: "HAI", code: "HAI", name: "ハイチ" },
    away: { id: "SCO", code: "SCO", name: "スコットランド" },
  },
  {
    id: "2026-06-13-D-01",
    kickoffLabel: "2026/6/13(土) グループD｜BCプレイス（バンクーバー）",
    home: { id: "AUS", code: "AUS", name: "オーストラリア" },
    away: { id: "FIFA_D", code: "FIFA", name: "FIFA D" },
  },
  {
    id: "2026-06-13-C-02",
    kickoffLabel: "2026/6/13(土) グループC｜ニューヨーク・ニュージャージー・スタジアム",
    home: { id: "BRA", code: "BRA", name: "ブラジル" },
    away: { id: "MAR", code: "MAR", name: "モロッコ" },
  },
  {
    id: "2026-06-13-B-01",
    kickoffLabel: "2026/6/13(土) グループB｜サンフランシスコ・ベイエリア・スタジアム",
    home: { id: "QAT", code: "QAT", name: "カタール" },
    away: { id: "SUI", code: "SUI", name: "スイス" },
  },
  {
    id: "2026-06-14-E-01",
    kickoffLabel: "2026/6/14(日) グループE｜フィラデルフィア・スタジアム",
    home: { id: "CIV", code: "CIV", name: "コートジボワール" },
    away: { id: "ECU", code: "ECU", name: "エクアドル" },
  },
  {
    id: "2026-06-14-E-02",
    kickoffLabel: "2026/6/14(日) グループE｜ヒューストン・スタジアム",
    home: { id: "GER", code: "GER", name: "ドイツ" },
    away: { id: "CUW", code: "CUW", name: "キュラソー" },
  },
  {
    id: "2026-06-14-F-01",
    kickoffLabel: "2026/6/14(日) グループF｜ダラス・スタジアム",
    home: { id: "NED", code: "NED", name: "オランダ" },
    away: { id: "JPN", code: "JPN", name: "日本" },
  },
  {
    id: "2026-06-14-F-02",
    kickoffLabel: "2026/6/14(日) グループF｜エスタディオ・モンテレイ",
    home: { id: "FIFA_F", code: "FIFA", name: "FIFA F" },
    away: { id: "TUN", code: "TUN", name: "チュニジア" },
  },
  {
    id: "2026-06-15-H-01",
    kickoffLabel: "2026/6/15(月) グループH｜マイアミ・スタジアム",
    home: { id: "KSA", code: "KSA", name: "サウジアラビア" },
    away: { id: "URU", code: "URU", name: "ウルグアイ" },
  },
  {
    id: "2026-06-15-H-02",
    kickoffLabel: "2026/6/15(月) グループH｜アトランタ・スタジアム",
    home: { id: "ESP", code: "ESP", name: "スペイン" },
    away: { id: "CPV", code: "CPV", name: "カーボベルデ" },
  },
  {
    id: "2026-06-15-G-01",
    kickoffLabel: "2026/6/15(月) グループG｜ロサンゼルス・スタジアム",
    home: { id: "IRN", code: "IRN", name: "イラン" },
    away: { id: "NZL", code: "NZL", name: "ニュージーランド" },
  },
  {
    id: "2026-06-15-G-02",
    kickoffLabel: "2026/6/15(月) グループG｜シアトル・スタジアム",
    home: { id: "BEL", code: "BEL", name: "ベルギー" },
    away: { id: "EGY", code: "EGY", name: "エジプト" },
  },
  {
    id: "2026-06-16-I-01",
    kickoffLabel: "2026/6/16(火) グループI｜ニューヨーク・ニュージャージー・スタジアム",
    home: { id: "FRA", code: "FRA", name: "フランス" },
    away: { id: "SEN", code: "SEN", name: "セネガル" },
  },
  {
    id: "2026-06-16-I-02",
    kickoffLabel: "2026/6/16(火) グループI｜ボストン・スタジアム",
    home: { id: "FIFA_I", code: "FIFA", name: "FIFA I" },
    away: { id: "NOR", code: "NOR", name: "ノルウェー" },
  },
  {
    id: "2026-06-16-J-01",
    kickoffLabel: "2026/6/16(火) グループJ｜カンザスシティ・スタジアム",
    home: { id: "ARG", code: "ARG", name: "アルゼンチン" },
    away: { id: "ALG", code: "ALG", name: "アルジェリア" },
  },
  {
    id: "2026-06-16-J-02",
    kickoffLabel: "2026/6/16(火) グループJ｜サンフランシスコ・ベイエリア・スタジアム",
    home: { id: "AUT", code: "AUT", name: "オーストリア" },
    away: { id: "JOR", code: "JOR", name: "ヨルダン" },
  },
  {
    id: "2026-06-17-L-01",
    kickoffLabel: "2026/6/17(水) グループL｜トロント・スタジアム",
    home: { id: "GHA", code: "GHA", name: "ガーナ" },
    away: { id: "PAN", code: "PAN", name: "パナマ" },
  },
  {
    id: "2026-06-17-L-02",
    kickoffLabel: "2026/6/17(水) グループL｜ダラス・スタジアム",
    home: { id: "ENG", code: "ENG", name: "イングランド" },
    away: { id: "CRO", code: "CRO", name: "クロアチア" },
  },
  {
    id: "2026-06-17-K-01",
    kickoffLabel: "2026/6/17(水) グループK｜ヒューストン・スタジアム",
    home: { id: "POR", code: "POR", name: "ポルトガル" },
    away: { id: "FIFA_K", code: "FIFA", name: "FIFA K" },
  },
  {
    id: "2026-06-17-K-02",
    kickoffLabel: "2026/6/17(水) グループK｜エスタディオ・アステカ（メキシコシティ）",
    home: { id: "UZB", code: "UZB", name: "ウズベキスタン" },
    away: { id: "COL", code: "COL", name: "コロンビア" },
  },
  {
    id: "2026-06-18-A-01",
    kickoffLabel: "2026/6/18(木) グループA｜アトランタ・スタジアム",
    home: { id: "FIFA_A", code: "FIFA", name: "FIFA A" },
    away: { id: "RSA", code: "RSA", name: "南アフリカ" },
  },
  {
    id: "2026-06-18-B-01",
    kickoffLabel: "2026/6/18(木) グループB｜ロサンゼルス・スタジアム",
    home: { id: "SUI", code: "SUI", name: "スイス" },
    away: { id: "FIFA_B", code: "FIFA", name: "FIFA B" },
  },
  {
    id: "2026-06-18-B-02",
    kickoffLabel: "2026/6/18(木) グループB｜BCプレイス（バンクーバー）",
    home: { id: "CAN", code: "CAN", name: "カナダ" },
    away: { id: "QAT", code: "QAT", name: "カタール" },
  },
  {
    id: "2026-06-18-A-02",
    kickoffLabel: "2026/6/18(木) グループA｜エスタディオ・グアダラハラ",
    home: { id: "MEX", code: "MEX", name: "メキシコ" },
    away: { id: "KOR", code: "KOR", name: "韓国" },
  },
  {
    id: "2026-06-19-C-01",
    kickoffLabel: "2026/6/19(金) グループC｜フィラデルフィア・スタジアム",
    home: { id: "BRA", code: "BRA", name: "ブラジル" },
    away: { id: "HAI", code: "HAI", name: "ハイチ" },
  },
  {
    id: "2026-06-19-C-02",
    kickoffLabel: "2026/6/19(金) グループC｜ボストン・スタジアム",
    home: { id: "SCO", code: "SCO", name: "スコットランド" },
    away: { id: "MAR", code: "MAR", name: "モロッコ" },
  },
  {
    id: "2026-06-19-D-01",
    kickoffLabel: "2026/6/19(金) グループD｜サンフランシスコ・ベイエリア・スタジアム",
    home: { id: "FIFA_D", code: "FIFA", name: "FIFA D" },
    away: { id: "PAR", code: "PAR", name: "パラグアイ" },
  },
  {
    id: "2026-06-19-D-02",
    kickoffLabel: "2026/6/19(金) グループD｜シアトル・スタジアム",
    home: { id: "USA", code: "USA", name: "アメリカ" },
    away: { id: "AUS", code: "AUS", name: "オーストラリア" },
  },
  {
    id: "2026-06-20-E-01",
    kickoffLabel: "2026/6/20(土) グループE｜トロント・スタジアム",
    home: { id: "GER", code: "GER", name: "ドイツ" },
    away: { id: "CIV", code: "CIV", name: "コートジボワール" },
  },
  {
    id: "2026-06-20-E-02",
    kickoffLabel: "2026/6/20(土) グループE｜カンザスシティ・スタジアム",
    home: { id: "ECU", code: "ECU", name: "エクアドル" },
    away: { id: "CUW", code: "CUW", name: "キュラソー" },
  },
  {
    id: "2026-06-20-F-01",
    kickoffLabel: "2026/6/20(土) グループF｜ヒューストン・スタジアム",
    home: { id: "NED", code: "NED", name: "オランダ" },
    away: { id: "FIFA_F", code: "FIFA", name: "FIFA F" },
  },
  {
    id: "2026-06-20-F-02",
    kickoffLabel: "2026/6/20(土) グループF｜エスタディオ・モンテレイ",
    home: { id: "TUN", code: "TUN", name: "チュニジア" },
    away: { id: "JPN", code: "JPN", name: "日本" },
  },
  {
    id: "2026-06-21-H-01",
    kickoffLabel: "2026/6/21(日) グループH｜マイアミ・スタジアム",
    home: { id: "URU", code: "URU", name: "ウルグアイ" },
    away: { id: "CPV", code: "CPV", name: "カーボベルデ" },
  },
  {
    id: "2026-06-21-H-02",
    kickoffLabel: "2026/6/21(日) グループH｜アトランタ・スタジアム",
    home: { id: "ESP", code: "ESP", name: "スペイン" },
    away: { id: "KSA", code: "KSA", name: "サウジアラビア" },
  },
  {
    id: "2026-06-21-G-01",
    kickoffLabel: "2026/6/21(日) グループG｜ロサンゼルス・スタジアム",
    home: { id: "BEL", code: "BEL", name: "ベルギー" },
    away: { id: "IRN", code: "IRN", name: "イラン" },
  },
  {
    id: "2026-06-21-G-02",
    kickoffLabel: "2026/6/21(日) グループG｜BCプレイス（バンクーバー）",
    home: { id: "NZL", code: "NZL", name: "ニュージーランド" },
    away: { id: "EGY", code: "EGY", name: "エジプト" },
  },
  {
    id: "2026-06-22-I-01",
    kickoffLabel: "2026/6/22(月) グループI｜ニューヨーク・ニュージャージー・スタジアム",
    home: { id: "NOR", code: "NOR", name: "ノルウェー" },
    away: { id: "SEN", code: "SEN", name: "セネガル" },
  },
  {
    id: "2026-06-22-I-02",
    kickoffLabel: "2026/6/22(月) グループI｜フィラデルフィア・スタジアム",
    home: { id: "FRA", code: "FRA", name: "フランス" },
    away: { id: "FIFA_I", code: "FIFA", name: "FIFA I" },
  },
  {
    id: "2026-06-22-J-01",
    kickoffLabel: "2026/6/22(月) グループJ｜ダラス・スタジアム",
    home: { id: "ARG", code: "ARG", name: "アルゼンチン" },
    away: { id: "AUT", code: "AUT", name: "オーストラリア" },
  },
  {
    id: "2026-06-22-J-02",
    kickoffLabel: "2026/6/22(月) グループJ｜サンフランシスコ・ベイエリア・スタジアム",
    home: { id: "JOR", code: "JOR", name: "ヨルダン" },
    away: { id: "ALG", code: "ALG", name: "アルジェリア" },
  },
  {
    id: "2026-06-23-L-01",
    kickoffLabel: "2026/6/23(火) グループL｜ボストン・スタジアム",
    home: { id: "ENG", code: "ENG", name: "イングランド" },
    away: { id: "GHA", code: "GHA", name: "ガーナ" },
  },
  {
    id: "2026-06-23-L-02",
    kickoffLabel: "2026/6/23(火) グループL｜トロント・スタジアム",
    home: { id: "PAN", code: "PAN", name: "パナマ" },
    away: { id: "CRO", code: "CRO", name: "クロアチア" },
  },
  {
    id: "2026-06-23-K-01",
    kickoffLabel: "2026/6/23(火) グループK｜ヒューストン・スタジアム",
    home: { id: "POR", code: "POR", name: "ポルトガル" },
    away: { id: "UZB", code: "UZB", name: "ウズベキスタン" },
  },
  {
    id: "2026-06-23-K-02",
    kickoffLabel: "2026/6/23(火) グループK｜エスタディオ・グアダラハラ",
    home: { id: "COL", code: "COL", name: "コロンビア" },
    away: { id: "FIFA_K", code: "FIFA", name: "FIFA K" },
  },
  {
    id: "2026-06-24-C-01",
    kickoffLabel: "2026/6/24(水) グループC｜マイアミ・スタジアム",
    home: { id: "SCO", code: "SCO", name: "スコットランド" },
    away: { id: "BRA", code: "BRA", name: "ブラジル" },
  },
  {
    id: "2026-06-24-C-02",
    kickoffLabel: "2026/6/24(水) グループC｜アトランタ・スタジアム",
    home: { id: "MAR", code: "MAR", name: "モロッコ" },
    away: { id: "HAI", code: "HAI", name: "ハイチ" },
  },
  {
    id: "2026-06-24-B-01",
    kickoffLabel: "2026/6/24(水) グループB｜BCプレイス（バンクーバー）",
    home: { id: "SUI", code: "SUI", name: "スイス" },
    away: { id: "CAN", code: "CAN", name: "カナダ" },
  },
  {
    id: "2026-06-24-B-02",
    kickoffLabel: "2026/6/24(水) グループB｜シアトル・スタジアム",
    home: { id: "FIFA_B", code: "FIFA", name: "FIFA B" },
    away: { id: "QAT", code: "QAT", name: "カタール" },
  },
  {
    id: "2026-06-24-A-01",
    kickoffLabel: "2026/6/24(水) グループA｜エスタディオ・アステカ（メキシコシティ）",
    home: { id: "FIFA_A", code: "FIFA", name: "FIFA A" },
    away: { id: "MEX", code: "MEX", name: "メキシコ" },
  },
  {
    id: "2026-06-24-A-02",
    kickoffLabel: "2026/6/24(水) グループA｜エスタディオ・モンテレイ",
    home: { id: "RSA", code: "RSA", name: "南アフリカ" },
    away: { id: "KOR", code: "KOR", name: "韓国" },
  },
  {
    id: "2026-06-25-E-01",
    kickoffLabel: "2026/6/25(木) グループE｜フィラデルフィア・スタジアム",
    home: { id: "CUW", code: "CUW", name: "キュラソー" },
    away: { id: "CIV", code: "CIV", name: "コートジボワール" },
  },
  {
    id: "2026-06-25-E-02",
    kickoffLabel: "2026/6/25(木) グループE｜ニューヨーク・ニュージャージー・スタジアム",
    home: { id: "ECU", code: "ECU", name: "エクアドル" },
    away: { id: "GER", code: "GER", name: "ドイツ" },
  },
  {
    id: "2026-06-25-F-01",
    kickoffLabel: "2026/6/25(木) グループF｜ダラス・スタジアム",
    home: { id: "JPN", code: "JPN", name: "日本" },
    away: { id: "FIFA_F", code: "FIFA", name: "FIFA F" },
  },
  {
    id: "2026-06-25-F-02",
    kickoffLabel: "2026/6/25(木) グループF｜カンザスシティ・スタジアム",
    home: { id: "TUN", code: "TUN", name: "チュニジア" },
    away: { id: "NED", code: "NED", name: "オランダ" },
  },
  {
    id: "2026-06-25-D-01",
    kickoffLabel: "2026/6/25(木) グループD｜ロサンゼルス・スタジアム",
    home: { id: "FIFA_D", code: "FIFA", name: "FIFA D" },
    away: { id: "USA", code: "USA", name: "アメリカ" },
  },
  {
    id: "2026-06-25-D-02",
    kickoffLabel: "2026/6/25(木) グループD｜サンフランシスコ・ベイエリア・スタジアム",
    home: { id: "PAR", code: "PAR", name: "パラグアイ" },
    away: { id: "AUS", code: "AUS", name: "オーストラリア" },
  },
  {
    id: "2026-06-26-I-01",
    kickoffLabel: "2026/6/26(金) グループI｜ボストン・スタジアム",
    home: { id: "NOR", code: "NOR", name: "ノルウェー" },
    away: { id: "FRA", code: "FRA", name: "フランス" },
  },
  {
    id: "2026-06-26-I-02",
    kickoffLabel: "2026/6/26(金) グループI｜トロント・スタジアム",
    home: { id: "SEN", code: "SEN", name: "セネガル" },
    away: { id: "FIFA_I", code: "FIFA", name: "FIFA I" },
  },
  {
    id: "2026-06-26-G-01",
    kickoffLabel: "2026/6/26(金) グループG｜シアトル・スタジアム",
    home: { id: "EGY", code: "EGY", name: "エジプト" },
    away: { id: "IRN", code: "IRN", name: "イラン" },
  },
  {
    id: "2026-06-26-G-02",
    kickoffLabel: "2026/6/26(金) グループG｜BCプレイス（バンクーバー）",
    home: { id: "NZL", code: "NZL", name: "ニュージーランド" },
    away: { id: "BEL", code: "BEL", name: "ベルギー" },
  },
  {
    id: "2026-06-26-H-01",
    kickoffLabel: "2026/6/26(金) グループH｜ヒューストン・スタジアム",
    home: { id: "CPV", code: "CPV", name: "カーボベルデ" },
    away: { id: "KSA", code: "KSA", name: "サウジアラビア" },
  },
  {
    id: "2026-06-26-H-02",
    kickoffLabel: "2026/6/26(金) グループH｜エスタディオ・グアダラハラ",
    home: { id: "URU", code: "URU", name: "ウルグアイ" },
    away: { id: "ESP", code: "ESP", name: "スペイン" },
  },
  {
    id: "2026-06-27-L-01",
    kickoffLabel: "2026/6/27(土) グループL｜ニューヨーク・ニュージャージー・スタジアム",
    home: { id: "PAN", code: "PAN", name: "パナマ" },
    away: { id: "ENG", code: "ENG", name: "イングランド" },
  },
  {
    id: "2026-06-27-L-02",
    kickoffLabel: "2026/6/27(土) グループL｜フィラデルフィア・スタジアム",
    home: { id: "CRO", code: "CRO", name: "クロアチア" },
    away: { id: "GHA", code: "GHA", name: "ガーナ" },
  },
  {
    id: "2026-06-27-J-01",
    kickoffLabel: "2026/6/27(土) グループJ｜カンザスシティ・スタジアム",
    home: { id: "ALG", code: "ALG", name: "アルジェリア" },
    away: { id: "AUT", code: "AUT", name: "オーストラリア" },
  },
  {
    id: "2026-06-27-J-02",
    kickoffLabel: "2026/6/27(土) グループJ｜ダラス・スタジアム",
    home: { id: "JOR", code: "JOR", name: "ヨルダン" },
    away: { id: "ARG", code: "ARG", name: "アルゼンチン" },
  },
  {
    id: "2026-06-27-K-01",
    kickoffLabel: "2026/6/27(土) グループK｜マイアミ・スタジアム",
    home: { id: "COL", code: "COL", name: "コロンビア" },
    away: { id: "POR", code: "POR", name: "ポルトガル" },
  },
  {
    id: "2026-06-27-K-02",
    kickoffLabel: "2026/6/27(土) グループK｜アトランタ・スタジアム",
    home: { id: "FIFA_K", code: "FIFA", name: "FIFA K" },
    away: { id: "UZB", code: "UZB", name: "ウズベキスタン" },
  },
];

export const WC2026_GROUPS: Record<string, Team[]> = {
  A: [
    { id: "MEX", code: "MEX", name: "メキシコ" },
    { id: "RSA", code: "RSA", name: "南アフリカ" },
    { id: "KOR", code: "KOR", name: "韓国" },
    { id: "FIFA_A", code: "FIFA", name: "FIFA A" },
  ],
  B: [
    { id: "CAN", code: "CAN", name: "カナダ" },
    { id: "FIFA_B", code: "FIFA", name: "FIFA B" },
    { id: "QAT", code: "QAT", name: "カタール" },
    { id: "SUI", code: "SUI", name: "スイス" },
  ],
  C: [
    { id: "BRA", code: "BRA", name: "ブラジル" },
    { id: "MAR", code: "MAR", name: "モロッコ" },
    { id: "HAI", code: "HAI", name: "ハイチ" },
    { id: "SCO", code: "SCO", name: "スコットランド" },
  ],
  D: [
    { id: "USA", code: "USA", name: "アメリカ" },
    { id: "PAR", code: "PAR", name: "パラグアイ" },
    { id: "AUS", code: "AUS", name: "オーストラリア" },
    { id: "FIFA_D", code: "FIFA", name: "FIFA D" },
  ],
  E: [
    { id: "GER", code: "GER", name: "ドイツ" },
    { id: "CUW", code: "CUW", name: "キュラソー" },
    { id: "CIV", code: "CIV", name: "コートジボワール" },
    { id: "ECU", code: "ECU", name: "エクアドル" },
  ],
  F: [
    { id: "NED", code: "NED", name: "オランダ" },
    { id: "JPN", code: "JPN", name: "日本" },
    { id: "FIFA_F", code: "FIFA", name: "FIFA F" },
    { id: "TUN", code: "TUN", name: "チュニジア" },
  ],
  G: [
    { id: "BEL", code: "BEL", name: "ベルギー" },
    { id: "EGY", code: "EGY", name: "エジプト" },
    { id: "IRN", code: "IRN", name: "イラン" },
    { id: "NZL", code: "NZL", name: "ニュージーランド" },
  ],
  H: [
    { id: "ESP", code: "ESP", name: "スペイン" },
    { id: "CPV", code: "CPV", name: "カーボベルデ" },
    { id: "KSA", code: "KSA", name: "サウジアラビア" },
    { id: "URU", code: "URU", name: "ウルグアイ" },
  ],
  I: [
    { id: "FRA", code: "FRA", name: "フランス" },
    { id: "SEN", code: "SEN", name: "セネガル" },
    { id: "FIFA_I", code: "FIFA", name: "FIFA I" },
    { id: "NOR", code: "NOR", name: "ノルウェー" },
  ],
  J: [
    { id: "ARG", code: "ARG", name: "アルゼンチン" },
    { id: "ALG", code: "ALG", name: "アルジェリア" },
    { id: "AUT", code: "AUT", name: "オーストリア" },
    { id: "JOR", code: "JOR", name: "ヨルダン" },
  ],
  K: [
    { id: "POR", code: "POR", name: "ポルトガル" },
    { id: "FIFA_K", code: "FIFA", name: "FIFA K" },
    { id: "UZB", code: "UZB", name: "ウズベキスタン" },
    { id: "COL", code: "COL", name: "コロンビア" },
  ],
  L: [
    { id: "ENG", code: "ENG", name: "イングランド" },
    { id: "CRO", code: "CRO", name: "クロアチア" },
    { id: "GHA", code: "GHA", name: "ガーナ" },
    { id: "PAN", code: "PAN", name: "パナマ" },
  ],
};
